name: Update the version

on: [push]

permissions: write-all

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Bump version
        uses: remorses/bump-version@js
        with:
            version_file: ./VERSION
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update logo
        run:
          python -m actions_workshop --version VERSION --base-logo logo_base.png --new-logo logo.png
